server:
  port: 8080
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.1.8:3306/springboot?serverTimezone=UTC
#    username: root
#    password: 5959932
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/ry-vue?stringtype=unspecified
    username: postgres
    password: 5959932
mybatis:
  type-aliases-package: com.example.model.Student
  mapper-locations: classpath:/mapper/*.xml
